version: "3.8"
services:
  app:
    # stdin_open: true
    # tty: true
    build: 
      context: .
      dockerfile: Dockerfile
    environment: 
      - FLASK_APP=service
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    command: gunicorn --bind 0.0.0.0:57633 "service:create_app()" --chdir service 
             #python -u -m flask run --host=0.0.0.0 --port=57633
    ports:
      - "57633:57633"
    volumes:
      - .:/python-flask